//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseIt
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense_report
    {
        public int ID { get; set; }
        public string Name_ { get; set; }
        public string Expense_Type { get; set; }
        public int Amount { get; set; }
        public string Department { get; set; }
    }
}
